### ISSUE TITLE
MAGIC perturbation files available?

### ISSUE THREAD

**Issue by Fergus-Hayes-Spire** [gemini3d/gemini-examples#1]
Hi Matthew,

I am new to ionospheric modelling and I am interested in learning how to use GEMINI given perturbations. I wish to run `your tohoku20113D_highres` example to find out how, however I do not see the necessary perturbation files available in any of the GEMINI repos. Could you possibly make your MAGIC simulation outputs for this example available?  

best wishes,
Fergus

**Comment by mattzett** [comment]
I've almost got all this together; just fighting with a weird bug that seems to have appeared at some point in the past few months...

**Comment by mattzett** [comment]
Okay got the bug fixed and updated documentation together for how to run this; just need to upload the files.  I'm new to Zenodo so it may take me a little bit to figure out out...

**Comment by Fergus-Hayes-Spire** [comment]
Thanks a lot! I'll give it a go and let you know how I get on.

**Comment by mattzett** [comment]
Okay I'm having to download the data from my server and then post on Zenodo - slow but it'll work...

**Comment by mattzett** [comment]
I can't get zenodo to accept the 20 GB of input files so I'm going to dump it on dropbox and send you a link to download...  Will let you know when that is ready.

**Comment by mattzett** [comment]
Okay I sent out an email with links for now; will close this out...
