### ISSUE TITLE
API Updates to examples

### ISSUE THREAD

**Issue by mattzett** [gemini3d/gemini-examples#2]
Someone needs to go through all of the examples and update them to use the new .nml config file format and also to use updated Matlab APIs.

**Comment by scivision** [comment]
This is a manual process, but I see a lot of the examples look like GDI_periodic_lowres which has been updated to reuse gemini-matlab functions where possible. It looks like perturb.m could be made part of gemini-matlab for even more de-duplication.

**Comment by mattzett** [comment]
I like the way you updated the GDI_periodic_lowres example; I'm going to try to replicate this with the other base example for our book chapter (KHI_periodic_lowres).

**Comment by mattzett** [comment]
Perturb is going to be specific to the type of simulation being done, so let's keep it in the examples repo for now...

**Comment by scivision** [comment]
Yes that's fine, as we see something is being used in several examples then maybe it makes sense (or not) to incorporate into the gemini-matlab repo. The biggest thing is to get things functionalized so they can be tested and deduplicated across examples.

**Comment by mattzett** [comment]
This is such a big task I think we need to prioritize these based on what people are requesting...  So far I've heard requests for:

1)  KHI (this is needed for our article, Michael will develop)
2) ARCS (Steve Kaeppler want to work on this, Matt will develop)

**Comment by mattzett** [comment]
I'm just going to leave this issue here as this work will be ongoing; as people want to use the examples, I'll update them.

**Comment by scivision** [comment]
This is now a Project on this repo
