### ISSUE TITLE
Reduce code repetition in Efield, precip, and patch generations scripts.  

### ISSUE THREAD

**Issue by mattzett** [gemini3d/gemini-examples#3]
Way too much copy-pasted code in the examples...

**Comment by scivision** [comment]
GDI_periodic_lowres is an example. I don't have a template for perturb.m in gemini-matlab, but one could be made from it. 

The overall idea is to use `isfield()` to see if a parameter exists, then apply it. Or switch statements based on field character value. I think that unique functions can exist in harmony with the base function set, for special cases.

**Comment by mattzett** [comment]
perturb.m is very problem specific and perhaps should be kept in each example directory for now...  Thanks for updating that one...

**Comment by mattzett** [comment]
ARCS, gdi_lowres, and khi_lowres now have examples of this
